# accum_grad: 1 #16

#frontend related
videofront: conv3d+resnet18
videofront_conf: 
    random: True,
    channel_input: bgr
    size: [88,88] 
    downsampling: False
    hidden_channel_num: 64 
    res_block_type: basic2d
    res_layer_block_num: 2
    res_hidden_channels: [ 64, 128, 256, 512 ]
    res_stride: [ 1, 2, 2, 2 ]
    res_act_type: prelu
    res_downsample_type: avgpool

#init model params
ignore_init_mismatch: True 
init_param: 
    - /train33/sppro/permanent/hangchen2/pandora/egs/misp2024-mmmt-minggao/examples/misp2022/s0/pretrain/conv3d_resnet18/lrw_resnet18_dctcn_video_boundary.pth
    - /train33/sppro/permanent/hangchen2/pandora/egs/misp2024-mmmt-minggao/examples/misp2022/s0/exp/asr_near_wenetspeech/avg_10.pt
name_map: 
    - {"video_frontend.video_frontend":"frontend3D",
      "video_frontend.resnet.layer0.0.conv1.0":"trunk.layer1.0.conv1",
      "video_frontend.resnet.layer0.0.conv1.1":"trunk.layer1.0.bn1",
      "video_frontend.resnet.layer0.0.conv2.0":"trunk.layer1.0.conv2",
      "video_frontend.resnet.layer0.0.conv2.1":"trunk.layer1.0.bn2",
      "video_frontend.resnet.layer0.1.conv1.0":"trunk.layer1.1.conv1",
      "video_frontend.resnet.layer0.1.conv1.1":"trunk.layer1.1.bn1",
      "video_frontend.resnet.layer0.1.conv2.0":"trunk.layer1.1.conv2",
      "video_frontend.resnet.layer0.1.conv2.1":"trunk.layer1.1.bn2",
      "video_frontend.resnet.layer1.0.conv1.0":"trunk.layer2.0.conv1",
      "video_frontend.resnet.layer1.0.conv1.1":"trunk.layer2.0.bn1",
      "video_frontend.resnet.layer1.0.conv2.0":"trunk.layer2.0.conv2",
      "video_frontend.resnet.layer1.0.conv2.1":"trunk.layer2.0.bn2",
      "video_frontend.resnet.layer1.0.downsample.process.1":"trunk.layer2.0.downsample.0",
      "video_frontend.resnet.layer1.0.downsample.process.2":"trunk.layer2.0.downsample.1",
      "video_frontend.resnet.layer1.1.conv1.0":"trunk.layer2.1.conv1",
      "video_frontend.resnet.layer1.1.conv1.1":"trunk.layer2.1.bn1",
      "video_frontend.resnet.layer1.1.conv2.0":"trunk.layer2.1.conv2",
      "video_frontend.resnet.layer1.1.conv2.1":"trunk.layer2.1.bn2",
      "video_frontend.resnet.layer2.0.conv1.0":"trunk.layer3.0.conv1",
      "video_frontend.resnet.layer2.0.conv1.1":"trunk.layer3.0.bn1",
      "video_frontend.resnet.layer2.0.conv2.0":"trunk.layer3.0.conv2",
      "video_frontend.resnet.layer2.0.conv2.1":"trunk.layer3.0.bn2",
      "video_frontend.resnet.layer2.0.downsample.process.1":"trunk.layer3.0.downsample.0",
      "video_frontend.resnet.layer2.0.downsample.process.2":"trunk.layer3.0.downsample.1",
      "video_frontend.resnet.layer2.1.conv1.0":"trunk.layer3.1.conv1",
      "video_frontend.resnet.layer2.1.conv1.1":"trunk.layer3.1.bn1",
      "video_frontend.resnet.layer2.1.conv2.0":"trunk.layer3.1.conv2",
      "video_frontend.resnet.layer2.1.conv2.1":"trunk.layer3.1.bn2",
      "video_frontend.resnet.layer3.0.conv1.0":"trunk.layer4.0.conv1",
      "video_frontend.resnet.layer3.0.conv1.1":"trunk.layer4.0.bn1",
      "video_frontend.resnet.layer3.0.conv2.0":"trunk.layer4.0.conv2",
      "video_frontend.resnet.layer3.0.conv2.1":"trunk.layer4.0.bn2",
      "video_frontend.resnet.layer3.0.downsample.process.1":"trunk.layer4.0.downsample.0",
      "video_frontend.resnet.layer3.0.downsample.process.2":"trunk.layer4.0.downsample.1",
      "video_frontend.resnet.layer3.1.conv1.0":"trunk.layer4.1.conv1",
      "video_frontend.resnet.layer3.1.conv1.1":"trunk.layer4.1.bn1",
      "video_frontend.resnet.layer3.1.conv2.0":"trunk.layer4.1.conv2",
      "video_frontend.resnet.layer3.1.conv2.1":"trunk.layer4.1.bn2"}
    - {"encoder":"encoder",
      "decoder":"decoder",
      "ctc":"ctc"}

# dataset
dataset_conf:
  batch_conf:
    batch_size: 2
    batch_type: static
  fbank_conf:
    dither: 1.0
    frame_length: 25
    frame_shift: 10
    num_mel_bins: 80
  filter_conf:
    max_length: 40960
    min_length: 0
    token_max_length: 200
    token_min_length: 1
  resample_conf:
    resample_rate: 16000
  shuffle: true
  shuffle_conf:
    shuffle_size: 1500
  sort: true
  sort_conf:
    sort_size: 500
  spec_aug: true
  spec_aug_conf:
    max_f: 10
    max_t: 50
    num_f_mask: 2
    num_t_mask: 2
  speed_perturb: true

# decoder
decoder: bitransformer
decoder_conf:
  attention_heads: 8
  dropout_rate: 0.1
  linear_units: 2048
  num_blocks: 3
  positional_dropout_rate: 0.1
  r_num_blocks: 3
  self_attention_dropout_rate: 0.1
  src_attention_dropout_rate: 0.1

# encoder
encoder: conformer
encoder_conf:
  activation_type: swish
  attention_dropout_rate: 0.1
  attention_heads: 8
  causal: true
  cnn_module_kernel: 15
  cnn_module_norm: layer_norm
  dropout_rate: 0.1
  input_layer: ''
  linear_units: 2048
  normalize_before: true
  num_blocks: 12
  output_size: 512
  pos_enc_layer_type: rel_pos
  positional_dropout_rate: 0.1
  selfattention_layer_type: rel_selfattn
  use_cnn_module: true
  use_dynamic_chunk: true
  use_dynamic_left_chunk: false

grad_clip: 5
input_dim: 80
is_json_cmvn: true
log_interval: 1000

max_epoch: 60
model_conf:
  ctc_weight: 0.3
  length_normalized_loss: false
  lsm_weight: 0.1
  reverse_weight: 0.3

optim: adam
optim_conf:
  lr: 0.0006
output_dim: 5538
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 25000
